// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ContactDocumentDataSlicesSlice = TestimoniesSliderSlice | HeroSlice;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | InformationCardSlice
  | TestimoniesSliderSlice
  | CasesGridSlice
  | FeaturesSlice
  | GradientBackgroundSlice
  | DataJourneySlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = ContactDocument | HomepageDocument;

/**
 * Primary content in *CasesGrid → Primary*
 */
export interface CasesGridSliceDefaultPrimary {
  /**
   * heading field in *CasesGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * group 1 label field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.group_1_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_1_label: prismic.KeyTextField;

  /**
   * group 2 label field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.group_2_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_2_label: prismic.KeyTextField;

  /**
   * button label field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * button link field in *CasesGrid → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *CasesGrid → Items*
 */
export interface CasesGridSliceDefaultItem {
  /**
   * item title field in *CasesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_title: prismic.KeyTextField;

  /**
   * item description field in *CasesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_description: prismic.KeyTextField;

  /**
   * item image field in *CasesGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  item_image: prismic.ImageField<never>;

  /**
   * belongs to group field in *CasesGrid → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].belongs_to_group
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  belongs_to_group: prismic.NumberField;

  /**
   * link field in *CasesGrid → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for CasesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CasesGridSliceDefaultPrimary>,
  Simplify<CasesGridSliceDefaultItem>
>;

/**
 * Primary content in *CasesGrid → Primary*
 */
export interface CasesGridSlice3GroupsPrimary {
  /**
   * heading field in *CasesGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * group 1 label field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.group_1_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_1_label: prismic.KeyTextField;

  /**
   * group 2 label field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.group_2_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_2_label: prismic.KeyTextField;

  /**
   * group 3 label field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.group_3_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_3_label: prismic.KeyTextField;

  /**
   * button label field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * button link field in *CasesGrid → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *CasesGrid → Items*
 */
export interface CasesGridSlice3GroupsItem {
  /**
   * item title field in *CasesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_title: prismic.KeyTextField;

  /**
   * item description field in *CasesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_description: prismic.KeyTextField;

  /**
   * item image field in *CasesGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  item_image: prismic.ImageField<never>;

  /**
   * belongs to group field in *CasesGrid → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].belongs_to_group
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  belongs_to_group: prismic.NumberField;

  /**
   * link field in *CasesGrid → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * 3Groups variation for CasesGrid Slice
 *
 * - **API ID**: `3Groups`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesGridSlice3Groups = prismic.SharedSliceVariation<
  "3Groups",
  Simplify<CasesGridSlice3GroupsPrimary>,
  Simplify<CasesGridSlice3GroupsItem>
>;

/**
 * Primary content in *CasesGrid → Primary*
 */
export interface CasesGridSliceNonGroupedPrimary {
  /**
   * heading field in *CasesGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;
}

/**
 * Primary content in *CasesGrid → Items*
 */
export interface CasesGridSliceNonGroupedItem {
  /**
   * item title field in *CasesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_title: prismic.KeyTextField;

  /**
   * item description field in *CasesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_description: prismic.KeyTextField;

  /**
   * item image field in *CasesGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  item_image: prismic.ImageField<never>;
}

/**
 * NonGrouped variation for CasesGrid Slice
 *
 * - **API ID**: `nonGrouped`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesGridSliceNonGrouped = prismic.SharedSliceVariation<
  "nonGrouped",
  Simplify<CasesGridSliceNonGroupedPrimary>,
  Simplify<CasesGridSliceNonGroupedItem>
>;

/**
 * Primary content in *CasesGrid → Primary*
 */
export interface CasesGridSliceNoHeadingNonGroupedPrimary {
  /**
   * group 1 label field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.group_1_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_1_label: prismic.KeyTextField;

  /**
   * group 2 label field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.group_2_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_2_label: prismic.KeyTextField;
}

/**
 * Primary content in *CasesGrid → Items*
 */
export interface CasesGridSliceNoHeadingNonGroupedItem {
  /**
   * item title field in *CasesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_title: prismic.KeyTextField;

  /**
   * item description field in *CasesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_description: prismic.KeyTextField;

  /**
   * item image field in *CasesGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  item_image: prismic.ImageField<never>;

  /**
   * belongs to group field in *CasesGrid → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].belongs_to_group
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  belongs_to_group: prismic.NumberField;
}

/**
 * NoHeadingNonGrouped variation for CasesGrid Slice
 *
 * - **API ID**: `noHeadingNonGrouped`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesGridSliceNoHeadingNonGrouped = prismic.SharedSliceVariation<
  "noHeadingNonGrouped",
  Simplify<CasesGridSliceNoHeadingNonGroupedPrimary>,
  Simplify<CasesGridSliceNoHeadingNonGroupedItem>
>;

/**
 * Primary content in *CasesGrid → Primary*
 */
export interface CasesGridSliceNonGroupedButtonPrimary {
  /**
   * heading field in *CasesGrid → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * button label field in *CasesGrid → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * button link field in *CasesGrid → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *CasesGrid → Items*
 */
export interface CasesGridSliceNonGroupedButtonItem {
  /**
   * item title field in *CasesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_title: prismic.KeyTextField;

  /**
   * item description field in *CasesGrid → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item_description: prismic.KeyTextField;

  /**
   * item image field in *CasesGrid → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cases_grid.items[].item_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  item_image: prismic.ImageField<never>;
}

/**
 * NonGroupedButton variation for CasesGrid Slice
 *
 * - **API ID**: `nonGroupedButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesGridSliceNonGroupedButton = prismic.SharedSliceVariation<
  "nonGroupedButton",
  Simplify<CasesGridSliceNonGroupedButtonPrimary>,
  Simplify<CasesGridSliceNonGroupedButtonItem>
>;

/**
 * Slice variation for *CasesGrid*
 */
type CasesGridSliceVariation =
  | CasesGridSliceDefault
  | CasesGridSlice3Groups
  | CasesGridSliceNonGrouped
  | CasesGridSliceNoHeadingNonGrouped
  | CasesGridSliceNonGroupedButton;

/**
 * CasesGrid Shared Slice
 *
 * - **API ID**: `cases_grid`
 * - **Description**: CasesGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CasesGridSlice = prismic.SharedSlice<
  "cases_grid",
  CasesGridSliceVariation
>;

/**
 * Primary content in *DataJourney → Primary*
 */
export interface DataJourneySliceDefaultPrimary {
  /**
   * heading field in *DataJourney → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: data_journey.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * link label field in *DataJourney → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: data_journey.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Primary content in *DataJourney → Items*
 */
export interface DataJourneySliceDefaultItem {
  /**
   * title field in *DataJourney → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: data_journey.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * subtitle field in *DataJourney → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: data_journey.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * description field in *DataJourney → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: data_journey.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * image field in *DataJourney → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: data_journey.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * link field in *DataJourney → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: data_journey.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for DataJourney Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DataJourneySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DataJourneySliceDefaultPrimary>,
  Simplify<DataJourneySliceDefaultItem>
>;

/**
 * Slice variation for *DataJourney*
 */
type DataJourneySliceVariation = DataJourneySliceDefault;

/**
 * DataJourney Shared Slice
 *
 * - **API ID**: `data_journey`
 * - **Description**: DataJourney
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DataJourneySlice = prismic.SharedSlice<
  "data_journey",
  DataJourneySliceVariation
>;

/**
 * Primary content in *Features → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * heading field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface FeaturesSliceDefaultItem {
  /**
   * title field in *Features → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * image field in *Features → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * button text field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * button link field in *Features → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  Simplify<FeaturesSliceDefaultItem>
>;

/**
 * Primary content in *Features → Primary*
 */
export interface FeaturesSliceLabeledFeaturesPrimary {
  /**
   * heading field in *Features → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface FeaturesSliceLabeledFeaturesItem {
  /**
   * title field in *Features → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * label field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * description field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * image field in *Features → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * button text field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * button link field in *Features → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * LabeledFeatures variation for Features Slice
 *
 * - **API ID**: `labeledFeatures`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceLabeledFeatures = prismic.SharedSliceVariation<
  "labeledFeatures",
  Simplify<FeaturesSliceLabeledFeaturesPrimary>,
  Simplify<FeaturesSliceLabeledFeaturesItem>
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation =
  | FeaturesSliceDefault
  | FeaturesSliceLabeledFeatures;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Primary content in *GradientBackground → Primary*
 */
export interface GradientBackgroundSliceDefaultPrimary {
  /**
   * heading field in *GradientBackground → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *GradientBackground → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * primary button text field in *GradientBackground → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.primary.primary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * primary button link field in *GradientBackground → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField;

  /**
   * secondary button text field in *GradientBackground → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * secondary button link field in *GradientBackground → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_button_link: prismic.LinkField;
}

/**
 * Default variation for GradientBackground Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GradientBackgroundSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GradientBackgroundSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *GradientBackground → Primary*
 */
export interface GradientBackgroundSliceTechPartnersPrimary {
  /**
   * heading field in *GradientBackground → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Primary content in *GradientBackground → Items*
 */
export interface GradientBackgroundSliceTechPartnersItem {
  /**
   * logo field in *GradientBackground → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * link field in *GradientBackground → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * TechPartners variation for GradientBackground Slice
 *
 * - **API ID**: `techPartners`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GradientBackgroundSliceTechPartners = prismic.SharedSliceVariation<
  "techPartners",
  Simplify<GradientBackgroundSliceTechPartnersPrimary>,
  Simplify<GradientBackgroundSliceTechPartnersItem>
>;

/**
 * Primary content in *GradientBackground → Primary*
 */
export interface GradientBackgroundSliceButtonedPrimary {
  /**
   * heading field in *GradientBackground → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * button text field in *GradientBackground → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * button link field in *GradientBackground → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *GradientBackground → Items*
 */
export interface GradientBackgroundSliceButtonedItem {
  /**
   * logo field in *GradientBackground → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * name field in *GradientBackground → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * details field in *GradientBackground → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gradient_background.items[].details
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  details: prismic.KeyTextField;
}

/**
 * Buttoned variation for GradientBackground Slice
 *
 * - **API ID**: `buttoned`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GradientBackgroundSliceButtoned = prismic.SharedSliceVariation<
  "buttoned",
  Simplify<GradientBackgroundSliceButtonedPrimary>,
  Simplify<GradientBackgroundSliceButtonedItem>
>;

/**
 * Slice variation for *GradientBackground*
 */
type GradientBackgroundSliceVariation =
  | GradientBackgroundSliceDefault
  | GradientBackgroundSliceTechPartners
  | GradientBackgroundSliceButtoned;

/**
 * GradientBackground Shared Slice
 *
 * - **API ID**: `gradient_background`
 * - **Description**: GradientBackground
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GradientBackgroundSlice = prismic.SharedSlice<
  "gradient_background",
  GradientBackgroundSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * primary button text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * primary button link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField;

  /**
   * secondary button text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * secondary button link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_button_link: prismic.LinkField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * data item heading field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].data_item_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  data_item_heading: prismic.KeyTextField;

  /**
   * data item subheading field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].data_item_subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  data_item_subheading: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceWithLinkPrimary {
  /**
   * heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * link label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * link url field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField;

  /**
   * image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * primary button text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * primary button link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField;

  /**
   * secondary button text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * secondary button link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_button_link: prismic.LinkField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceWithLinkItem {
  /**
   * data item subheading field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].data_item_subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  data_item_subheading: prismic.KeyTextField;

  /**
   * data item heading field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].data_item_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  data_item_heading: prismic.KeyTextField;
}

/**
 * WithLink variation for Hero Slice
 *
 * - **API ID**: `withLink`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceWithLink = prismic.SharedSliceVariation<
  "withLink",
  Simplify<HeroSliceWithLinkPrimary>,
  Simplify<HeroSliceWithLinkItem>
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceTextOnlyPrimary {
  /**
   * heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * TextOnly variation for Hero Slice
 *
 * - **API ID**: `textOnly`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceTextOnly = prismic.SharedSliceVariation<
  "textOnly",
  Simplify<HeroSliceTextOnlyPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceTextOnlyWithDescriptionPrimary {
  /**
   * heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * description field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * TextOnlyWithDescription variation for Hero Slice
 *
 * - **API ID**: `textOnlyWithDescription`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceTextOnlyWithDescription = prismic.SharedSliceVariation<
  "textOnlyWithDescription",
  Simplify<HeroSliceTextOnlyWithDescriptionPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceSingleButtonPrimary {
  /**
   * heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * description field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * primary button text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * primary button link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.primary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  primary_button_link: prismic.LinkField;
}

/**
 * SingleButton variation for Hero Slice
 *
 * - **API ID**: `singleButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSingleButton = prismic.SharedSliceVariation<
  "singleButton",
  Simplify<HeroSliceSingleButtonPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceNoBackgroundPrimary {
  /**
   * heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * link label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * link url field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField;

  /**
   * image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * default button text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.default_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  default_button_text: prismic.KeyTextField;

  /**
   * default button link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.default_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  default_button_link: prismic.LinkField;

  /**
   * secondary button text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * secondary button link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_button_link: prismic.LinkField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceNoBackgroundItem {
  /**
   * data item heading field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].data_item_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  data_item_heading: prismic.KeyTextField;

  /**
   * data item subheading field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].data_item_subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  data_item_subheading: prismic.KeyTextField;
}

/**
 * NoBackground variation for Hero Slice
 *
 * - **API ID**: `noBackground`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceNoBackground = prismic.SharedSliceVariation<
  "noBackground",
  Simplify<HeroSliceNoBackgroundPrimary>,
  Simplify<HeroSliceNoBackgroundItem>
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceSingleButtonNoGradientPrimary {
  /**
   * heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * image field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * default button text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.default_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  default_button_text: prismic.KeyTextField;

  /**
   * default button link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.default_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  default_button_link: prismic.LinkField;
}

/**
 * SingleButtonNoGradient variation for Hero Slice
 *
 * - **API ID**: `singleButtonNoGradient`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSingleButtonNoGradient = prismic.SharedSliceVariation<
  "singleButtonNoGradient",
  Simplify<HeroSliceSingleButtonNoGradientPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceFormPrimary {
  /**
   * heading field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * secondary button text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * secondary button link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.secondary_button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  secondary_button_link: prismic.LinkField;

  /**
   * first name label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.first_name_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_name_label: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceFormItem {
  /**
   * input label field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].input_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_label: prismic.KeyTextField;

  /**
   * input placeholder field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].input_placeholder
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  input_placeholder: prismic.KeyTextField;
}

/**
 * Form variation for Hero Slice
 *
 * - **API ID**: `form`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceForm = prismic.SharedSliceVariation<
  "form",
  Simplify<HeroSliceFormPrimary>,
  Simplify<HeroSliceFormItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceWithLink
  | HeroSliceTextOnly
  | HeroSliceTextOnlyWithDescription
  | HeroSliceSingleButton
  | HeroSliceNoBackground
  | HeroSliceSingleButtonNoGradient
  | HeroSliceForm;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *InformationCard → Primary*
 */
export interface InformationCardSliceDefaultPrimary {
  /**
   * heading field in *InformationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *InformationCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * image field in *InformationCard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for InformationCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformationCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InformationCardSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *InformationCard → Primary*
 */
export interface InformationCardSliceHorizontalWithButtonPrimary {
  /**
   * heading field in *InformationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *InformationCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * image field in *InformationCard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * button label field in *InformationCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * button link field in *InformationCard → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * HorizontalWithButton variation for InformationCard Slice
 *
 * - **API ID**: `horizontalWithButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformationCardSliceHorizontalWithButton =
  prismic.SharedSliceVariation<
    "horizontalWithButton",
    Simplify<InformationCardSliceHorizontalWithButtonPrimary>,
    never
  >;

/**
 * Primary content in *InformationCard → Primary*
 */
export interface InformationCardSliceHorizontalAdditionalTextPrimary {
  /**
   * heading field in *InformationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *InformationCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * image field in *InformationCard → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * card heading field in *InformationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.card_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_heading: prismic.RichTextField;

  /**
   * card big text field in *InformationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.card_big_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_big_text: prismic.RichTextField;

  /**
   * card text content field in *InformationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.card_text_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_text_content: prismic.RichTextField;
}

/**
 * HorizontalAdditionalText variation for InformationCard Slice
 *
 * - **API ID**: `horizontalAdditionalText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformationCardSliceHorizontalAdditionalText =
  prismic.SharedSliceVariation<
    "horizontalAdditionalText",
    Simplify<InformationCardSliceHorizontalAdditionalTextPrimary>,
    never
  >;

/**
 * Primary content in *InformationCard → Primary*
 */
export interface InformationCardSliceHorizontalDualContentPrimary {
  /**
   * heading field in *InformationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * subheading field in *InformationCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * group 1 label field in *InformationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.group_1_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  group_1_label: prismic.RichTextField;

  /**
   * group 2 label field in *InformationCard → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.group_2_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  group_2_label: prismic.RichTextField;

  /**
   * group 1 disclaimer field in *InformationCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.group_1_disclaimer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_1_disclaimer: prismic.KeyTextField;

  /**
   * group 2 disclaimer field in *InformationCard → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.primary.group_2_disclaimer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  group_2_disclaimer: prismic.KeyTextField;
}

/**
 * Primary content in *InformationCard → Items*
 */
export interface InformationCardSliceHorizontalDualContentItem {
  /**
   * bandwidth unit field in *InformationCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: information_card.items[].bandwidth_unit
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  bandwidth_unit: prismic.KeyTextField;
}

/**
 * HorizontalDualContent variation for InformationCard Slice
 *
 * - **API ID**: `horizontalDualContent`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformationCardSliceHorizontalDualContent =
  prismic.SharedSliceVariation<
    "horizontalDualContent",
    Simplify<InformationCardSliceHorizontalDualContentPrimary>,
    Simplify<InformationCardSliceHorizontalDualContentItem>
  >;

/**
 * Slice variation for *InformationCard*
 */
type InformationCardSliceVariation =
  | InformationCardSliceDefault
  | InformationCardSliceHorizontalWithButton
  | InformationCardSliceHorizontalAdditionalText
  | InformationCardSliceHorizontalDualContent;

/**
 * InformationCard Shared Slice
 *
 * - **API ID**: `information_card`
 * - **Description**: InformationCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InformationCardSlice = prismic.SharedSlice<
  "information_card",
  InformationCardSliceVariation
>;

/**
 * Primary content in *TestimoniesSlider → Primary*
 */
export interface TestimoniesSliderSliceDefaultPrimary {
  /**
   * heading field in *TestimoniesSlider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies_slider.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * description field in *TestimoniesSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies_slider.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *TestimoniesSlider → Items*
 */
export interface TestimoniesSliderSliceDefaultItem {
  /**
   * name field in *TestimoniesSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies_slider.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * review field in *TestimoniesSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonies_slider.items[].review
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  review: prismic.KeyTextField;
}

/**
 * Default variation for TestimoniesSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimoniesSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimoniesSliderSliceDefaultPrimary>,
  Simplify<TestimoniesSliderSliceDefaultItem>
>;

/**
 * Slice variation for *TestimoniesSlider*
 */
type TestimoniesSliderSliceVariation = TestimoniesSliderSliceDefault;

/**
 * TestimoniesSlider Shared Slice
 *
 * - **API ID**: `testimonies_slider`
 * - **Description**: TestimoniesSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimoniesSliderSlice = prismic.SharedSlice<
  "testimonies_slider",
  TestimoniesSliderSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CasesGridSlice,
      CasesGridSliceDefaultPrimary,
      CasesGridSliceDefaultItem,
      CasesGridSlice3GroupsPrimary,
      CasesGridSlice3GroupsItem,
      CasesGridSliceNonGroupedPrimary,
      CasesGridSliceNonGroupedItem,
      CasesGridSliceNoHeadingNonGroupedPrimary,
      CasesGridSliceNoHeadingNonGroupedItem,
      CasesGridSliceNonGroupedButtonPrimary,
      CasesGridSliceNonGroupedButtonItem,
      CasesGridSliceVariation,
      CasesGridSliceDefault,
      CasesGridSlice3Groups,
      CasesGridSliceNonGrouped,
      CasesGridSliceNoHeadingNonGrouped,
      CasesGridSliceNonGroupedButton,
      DataJourneySlice,
      DataJourneySliceDefaultPrimary,
      DataJourneySliceDefaultItem,
      DataJourneySliceVariation,
      DataJourneySliceDefault,
      FeaturesSlice,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceDefaultItem,
      FeaturesSliceLabeledFeaturesPrimary,
      FeaturesSliceLabeledFeaturesItem,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      FeaturesSliceLabeledFeatures,
      GradientBackgroundSlice,
      GradientBackgroundSliceDefaultPrimary,
      GradientBackgroundSliceTechPartnersPrimary,
      GradientBackgroundSliceTechPartnersItem,
      GradientBackgroundSliceButtonedPrimary,
      GradientBackgroundSliceButtonedItem,
      GradientBackgroundSliceVariation,
      GradientBackgroundSliceDefault,
      GradientBackgroundSliceTechPartners,
      GradientBackgroundSliceButtoned,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceWithLinkPrimary,
      HeroSliceWithLinkItem,
      HeroSliceTextOnlyPrimary,
      HeroSliceTextOnlyWithDescriptionPrimary,
      HeroSliceSingleButtonPrimary,
      HeroSliceNoBackgroundPrimary,
      HeroSliceNoBackgroundItem,
      HeroSliceSingleButtonNoGradientPrimary,
      HeroSliceFormPrimary,
      HeroSliceFormItem,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceWithLink,
      HeroSliceTextOnly,
      HeroSliceTextOnlyWithDescription,
      HeroSliceSingleButton,
      HeroSliceNoBackground,
      HeroSliceSingleButtonNoGradient,
      HeroSliceForm,
      InformationCardSlice,
      InformationCardSliceDefaultPrimary,
      InformationCardSliceHorizontalWithButtonPrimary,
      InformationCardSliceHorizontalAdditionalTextPrimary,
      InformationCardSliceHorizontalDualContentPrimary,
      InformationCardSliceHorizontalDualContentItem,
      InformationCardSliceVariation,
      InformationCardSliceDefault,
      InformationCardSliceHorizontalWithButton,
      InformationCardSliceHorizontalAdditionalText,
      InformationCardSliceHorizontalDualContent,
      TestimoniesSliderSlice,
      TestimoniesSliderSliceDefaultPrimary,
      TestimoniesSliderSliceDefaultItem,
      TestimoniesSliderSliceVariation,
      TestimoniesSliderSliceDefault,
    };
  }
}
