// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cases_grid: dynamic(() => import("./CasesGrid")),
  data_journey: dynamic(() => import("./DataJourney")),
  features: dynamic(() => import("./Features")),
  gradient_background: dynamic(() => import("./GradientBackground")),
  hero: dynamic(() => import("./Hero")),
  information_card: dynamic(() => import("./InformationCard")),
  testimonies_slider: dynamic(() => import("./TestimoniesSlider")),
};
